### PR TITLE
Disable heartbeats If server not using it, but…

### PR DESCRIPTION
**Pull request by sega-yarkin**
Disable heartbeats If server not using it, but prefer our own heartbeat value from parameters in seconds

### CODE REVIEW

**Comment by sega-yarkin** [comment]
I'm using RabbitMQ with heartbeat=0, when the client received `data.heartbeat`=0 and `heartbeat`=true, it `setInterval( ..., 0*1000 )`.
But if RabbitMQ is not using heartbeats it can still respond to it.

**Comment by bakkerthehacker** [comment]
It is a bug that allows the `data.heartbeat = 0` case to slip through. 

However, I don't want to add numbers to the heartbeat parameter for `openAMQPCommunication`. If more advanced heartbeating is needed, then the client should call `connection.tune-ok` directly.

**Comment by sega-yarkin** [comment]
@bakkerthehacker 
Can you give some example how I can do that after handle.openAMQPCommunication? Thanks.

**Comment by sega-yarkin** [comment]
@bakkerthehacker 
If I run `connection.tune-ok` after `handle.openAMQPCommunication` RabbitMQ close connection with error `unexpected method in connection state running 'connection.tune_ok'`. What's wrong?

**Comment by bakkerthehacker** [comment]
Currently there is no easy way to replace only one part of the `openAMQPCommunication` method list.  To have a custom `connection.tune` will require calling all of the necessary initialization methods instead of `openAMQPCommunication`, as `connection.tune` is called during this process and cannot be called afterwards.  These methods are described in the docs [here](https://github.com/bakkerthehacker/bramqp/blob/master/doc/OtherHandleFunctions.md#handleopenamqpcommunicationusername-password-heartbeat-vhost-callbackerror) and listed in the code [here](https://github.com/bakkerthehacker/bramqp/blob/master/lib/connectionHandle.js#L212-L311).

I am also planning on writing some advanced tutorials that don't use `openAMQPCommunication` to demonstrate these cases.  See issue #36

**Comment by sega-yarkin** [comment]
I think it will so low level, in my case I just need to control heartbeats. I did some fixes in my fork and use its, I just need to say to server that I'll use heartbeats and he needs to answer me (rabbitmq don't answer if `tune-ok` was with `heartbeat = 0`).

P.S. And look at line https://github.com/bakkerthehacker/bramqp/blob/master/lib/connectionHandle.js#L291 , maybe it should be `'1:channel.close'`?

**Comment by bakkerthehacker** [comment]
You are correct, thanks for finding that!  I have gone through the entire library and added all the channel scoping where necessary.

**Comment by giorni** [comment]
Hi @bakkerthehacker, Can you explain the reason to not accept the heartbeat parameter as a number?

**Comment by bakkerthehacker** [comment]
I have been very hesitant about modifying any of the parameters in `openAMQPCommunication`.  It is a common function and it could easily become cluttered with features that very few clients use.  

However, seeing as you both have expressed interest in modifying the heartbeats, I can look into expanding the parameter.

**Comment by bakkerthehacker** [comment]
This has been added in 54ad17db and published in 0.3.7

**Pull request closed without merging**
