### PR TITLE
tls connections are broken in node 0.10.x

### PR DESCRIPTION
**Pull request by iainb**
See: https://github.com/joyent/node/issues/8499

This would have saved me a lot of time, currently the latest release of Ubuntu (15.04) ships with node.js 0.10.x.

### CODE REVIEW

**Comment by bakkerthehacker** [comment]
This is a bug, not a doc issue.  I would like to support tls on all supported node versions and 0.10.x definitely is being used. 

This bug was introduced when I changed the initialization code and assumed the node api would be consistent between 0.12.x and 0.10.x (DOH!)

> This would have saved me a lot of time

Sorry about the time spent on this :(

I can get a fix for it and a tls test written.  Travis will test it on all supported node versions

**Comment by iainb** [comment]
I was hoping you might treat it as a bug :+1: feel free to close this pull req whenever suits you.

As an aside, it would be useful to include the supported/targeted node.js versions in the README.md I would have raised this as a bug had I known 0.10.x was definitely supported.

**Comment by iainb** [comment]
Also, I'm happy to help test the fix when its ready.

**Comment by bakkerthehacker** [comment]
This has been fixed in 899f0e75 and published in 0.3.4

I have a test written as well, but I can't seem to configure Travis properly to set up TLS on the RabbitMQ, so it still needs some work.  I would rather get the fix out right away.

Thanks for bringing this up.  If there is anything else, feel free to open another issue.

**Pull request closed without merging**
