### PR TITLE
Connection state fix

### PR DESCRIPTION
**Pull request by NumminorihSF**
This PR depends on https://github.com/bakkerthehacker/bramqp/pull/49.
Now, no heartbeats will send after closing socket. No any serialize function will be called, if socket is closed. 
Also, if socket closing, `handle` object will emits `'close'` event.

### CODE REVIEW

**Comment by bakkerthehacker** [comment]
Hi!  Thanks for submitting this PR.  A couple of points to look at before merging this in

- The `clearTimeout` / `clearInterval` is definitely a bug, thanks for finding it!  Clearing on socket close also seems correct here.  However its mixed in with a few other commits/reverts that clutter up the git history.  Cherry picking this commit will fix this.  The commits for socket connection could also use some squashing.  

- Adding checks on the state of the socket to each function is interesting.  However, the socket has its own state, `socket.readyState` which I would use instead of `_connected`

- If `_connected` is removed, then emitting `'close'` on the connectionHandle doesn’t really accomplish anything.  Client's could listen on the socket and would perform the same thing.  I would remove this.  

- The socket check is called several times throughout the file.  The check is the same everywhere, except in the method functions, which also can emit `'error'`.  I would remove the `'error'` version and stick to a callback one if possible.  

- There may be some other locations that could check the state of the socket before proceeding, even adding it to the `ConnectionHandle` constructor may be useful.  

All around this looks pretty good.  I can get to cherry picking these things this week if you don’t get around to it.

**Comment by NumminorihSF** [comment]
* I didn't know about `socket.readyState` and didn't find this at doc of nodejs, but it works. I just afraid, that `socket.readyState` will not work on every version of node (it is not in public doc).
* Socket state check will allow to make faster spawning  callback with error.
* I will remove `.emit('close')` (socket is an argument to initialize, so it is more logically, to watch its event not in lib)

**Comment by NumminorihSF** [comment]
What about this?

**Comment by NumminorihSF** [comment]
Also, there is a fix for problem:
If socket already connected (fpr example, in previous event loop). Bramqp will never be initialize.

**Comment by bakkerthehacker** [comment]
This has been squashed into commit e190abca, merged into master and published to npm in 0.4.0 along with the spec update.  I have also added the same check to the hearbeat function as it also ends up calling `socket.write`.  Nice work on all of these changes.  :+1:

**Pull request closed without merging**
